### ISSUE TITLE
Solution fails when pulling from local feed service

### ISSUE THREAD

**Issue by gitisz** [piral-samples/angular-lazy-loading#1] opened 2022-11-26 15:06 UTC
Running this sample works when debugging with `npx pilet debug`.  However after publishing to a local feed, and when debugging the application shell with `npx piral debug`, routing to the Sample page results in the following errors:
```
Unable to resolve bare specifier 'angular-compiler.js' from http://localhost:1234/ (SystemJS Error#8 https://git.io/JvFET#8)
at throwUnresolved (system.js:510:1)
    at systemJSPrototype.resolve (system.js:507:1)
    at systemJSPrototype.resolve (system.js:791:1)
    at System.constructor.resolve (system.js:966:1)
    at System.constructor.resolve (debug.js:166:1)
    at system.js:144:1

The above error occurred in one of your React components:

    at Lazy
    at Suspense
    at ErrorBoundary (http://localhost:1234/index.js:6149:9)
    ...

Exception in component of type "page". Error: Unable to resolve bare specifier 'angular-compiler.js' from http://localhost:1234/ (SystemJS Error#8 https://git.io/JvFET#8)
    at throwUnresolved (system.js:510:1)
    at systemJSPrototype.resolve (system.js:507:1)
    at systemJSPrototype.resolve (system.js:791:1)
    at System.constructor.resolve (system.js:966:1)
    at System.constructor.resolve (debug.js:166:1)
    at system.js:144:1
```

This sample was run from an unmodified piral instance.

**Comment by FlorianRappl** [comment] 2022-11-27 06:53
I'd check if that sample feed service / local feed correctly transports the dependencies. They should look like

```json
[
  {
    "name": "isz-ang1-module",
    "version": "1.0.0",
    "link": "http://localhost:9000/files/isz-ang1-module/1.0.0/index.js",
    "spec": "v2",
    "requireRef": "webpackChunkpr_angularlazyloading",
    "dependencies": {
      "@angular/common@13.3.4": "http://localhost:9000/files/isz-ang1-module/1.0.0/angular-common.js",
      "@angular/compiler@13.3.4": "http://localhost:9000/files/isz-ang1-module/1.0.0/angular-compiler.js",
      "@angular/core@13.3.4": "http://localhost:9000/files/isz-ang1-module/1.0.0/angular-core.js",
      "@angular/platform-browser@13.3.4": "http://localhost:9000/files/isz-ang1-module/1.0.0/angular-platform-browser.js",
      "@angular/platform-browser-dynamic@13.3.4": "http://localhost:9000/files/isz-ang1-module/1.0.0/angular-platform-browser-dynamic.js",
      "@angular/forms@13.3.4": "http://localhost:9000/files/isz-ang1-module/1.0.0/angular-forms.js",
      "@angular/router@13.3.4": "http://localhost:9000/files/isz-ang1-module/1.0.0/angular-router.js"
    }
  }
]
```

The full feed service (https://www.piral.cloud/) does this. So I'd say this is less an issue with the sample pilet / repository and more with the sample feed service.

**Comment by gitisz** [comment] 2022-11-27 15:44
Not sure if you are taking PRs, and probably the source for the cloud version might be a better option here. But LMK, otherwise happy to close.  Thanks for the help!

**Comment by FlorianRappl** [comment] 2022-11-27 17:59
The cloud version is not open-source (and it also does not have this issue as pointed out - these are two completely different implementations).

Let's close this one here as the issue's root cause is not in this repo.

**Closed as completed by FlorianRappl** 2022-11-27 17:59 UTC
